services:

  mongo.db.catalog:
    image: mongo
    container_name: mongo.db.catalog.container
    restart: always
    ports:
        - 27030:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_catalog_data:/data/db

  mongo.db.catalog.ui:
    image: mongo-express
    container_name: mongo.db.catalog.ui.container
    restart: always
    ports:
      - 27032:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.catalog:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo_catalog_data: