@baseUrl = http://localhost:5262/api

GET {{baseUrl}}/categories/
Accept: application/json

###

POST {{baseUrl}}/categories/
Accept: application/json
Content-Type: application/json
{
  "name": "New Category",
}
###
